#!/usr/bin/env bash
# Clipboard sync and SSH config.
#
# Clipboard path (see setup/README.md for the diagram):
#   remote tmux/nvim -> lemonade relay on the remote host -> reverse SSH tunnel
#   -> lemonade server on the laptop -> system clipboard.
# The relay exists so processes that cannot reach the tunnel's loopback port
# (containers, other users' namespaces) still have one address to talk to.

step_clipboard() {
  if [ "${TARGET}" = "macos" ]; then
    # Server side: built from source so it works on Apple Silicon.
    if [ ! -x "${HOME}/go/bin/lemonade" ]; then
      have go || die "go is required to build lemonade on macOS."
      # Same version as the Linux release below: two machines on either end of
      # one clipboard should not be running different lemonades.
      go install "github.com/lemonade-command/lemonade@${LEMONADE_VERSION}"
    fi
  else
    install_release_binary lemonade \
      "https://github.com/lemonade-command/lemonade/releases/download/${LEMONADE_VERSION}/lemonade_linux_amd64.tar.gz"
    # Containers and other processes need the host address to reach the relay.
    hostname -I 2> /dev/null | awk '{print $1}' > "${XDG_CONFIG_HOME}/host_ip" || true
  fi
}

# ~/.ssh/config is generated in full mode and left strictly alone in layer mode,
# where the whole layer lives in ~/.ssh/config.d/ instead. That directory is the
# one place two setups can both write without an ordering problem, which is why
# the fragments are named by LAYER_SUFFIX -- a second instantiation gets its own
# file rather than overwriting this one.
step_ssh() {
  ensure_modern_python3
  local hosts="${DEV_SETUP_DIR}/config/ssh/hosts.toml"
  if [ ! -f "${hosts}" ]; then
    warn "no ${hosts}; skipping SSH config generation (see BOOTSTRAP.md)."
    return 0
  fi

  local d="${HOME}/.ssh/config.d"
  mkdir -p "${d}"
  chmod 700 "${HOME}/.ssh"

  if [ "${DEVSETUP_MODE}" = "full" ]; then
    backup_path "${HOME}/.ssh/config"
    write_generated "${HOME}/.ssh/config" \
      "${DEV_SETUP_DIR}/config/bin/hosts" ssh-config --base
    chmod 600 "${HOME}/.ssh/config"
    # A leftover from a machine that was once in layer mode would otherwise
    # duplicate every Host block that is now in ~/.ssh/config itself.
    rm -f "${d}/${LAYER_SUFFIX}-hosts"
  else
    # A hand-written file can already sit at exactly this name -- ~/.ssh/config.d
    # is where people put ssh fragments, and LAYER_SUFFIX is chosen to be the
    # obvious word for this setup. Overwriting it with `>` destroyed it silently.
    # Everything this script generates carries the header below, so its absence
    # is what distinguishes somebody's file from last run's output.
    local fragment="${d}/${LAYER_SUFFIX}-hosts"
    if [ -f "${fragment}" ] && ! head -1 "${fragment}" | grep -q 'Generated by setup/config/bin/hosts'; then
      backup_path "${fragment}"
    fi
    write_generated "${fragment}" \
      "${DEV_SETUP_DIR}/config/bin/hosts" ssh-config --fragment
    chmod 600 "${fragment}"
    ensure_ssh_config_include
  fi

  # Suffixed like the hosts fragment, and for the same reason: two
  # instantiations sharing a machine both reach this code (step_ssh runs in
  # BOTH modes), and unsuffixed names meant each install silently overwrote the
  # other's forwards — the one collision the config.d design was supposed to
  # prevent. The unsuffixed leftovers from before are removed.
  rm -f "${d}/generated-port-forwards" "${d}/custom-forwards"

  local generated="${d}/${LAYER_SUFFIX}-generated-port-forwards"
  "${DEV_SETUP_DIR}/config/bin/hosts" ssh-config --forwards > "${generated}"
  chmod 600 "${generated}"

  local custom="${DEV_SETUP_DIR}/config/ssh/custom-forwards"
  if [ -f "${custom}" ]; then
    cp "${custom}" "${d}/${LAYER_SUFFIX}-custom-forwards"
    chmod 600 "${d}/${LAYER_SUFFIX}-custom-forwards"
  fi

  check_git_ssh_key
}

# The key itself can never be in this repo, and it is generated per machine on
# purpose -- so on a fresh box the config above points at a file that does not
# exist yet. Left silent, that surfaces much later as `git fetch` failing with
# "Permission denied (publickey)", or as a project step skipping half the repos
# with a vague "access? ssh key?". Say it here, with the commands.
check_git_ssh_key() {
  local identity
  identity="$("${DEV_SETUP_DIR}/config/bin/hosts" identity 2>/dev/null)" || return 0
  [ -n "${identity}" ] || return 0
  identity="${identity/#\~/${HOME}}"

  if [ ! -f "${identity}" ]; then
    warn "no ssh key at ${identity}; every git@github.com remote will fail. Create it:"
    printf '    ssh-keygen -t ed25519 -C "%s" -f %s\n' "${GIT_USER_EMAIL:-you@example.com}" "${identity}"
    printf '    gh auth refresh -h github.com -s admin:public_key\n'
    printf '    gh ssh-key add %s.pub --title "$(hostname -s)"\n' "${identity}"
    return 0
  fi

  # The key exists but may not be registered on the account -- same error, same
  # confusion. One cheap probe: github answers a successful auth on stderr and
  # exits 1 either way, so match the message, never the status.
  #
  # Captured into a variable rather than piped into grep: install.sh runs under
  # `set -o pipefail`, where ssh's unconditional exit 1 becomes the pipeline's
  # status and a *successful* auth reads as a failure. That is not theoretical
  # -- it warned on every run of this step until the pipe went away.
  # ConnectTimeout rather than `timeout 15 ssh ...`: coreutils' timeout does not
  # exist on macOS, and "command not found" in the probe matched nothing, so the
  # laptop warned about a key github had in fact accepted.
  have ssh || return 0
  local probe
  probe="$(ssh -o StrictHostKeyChecking=accept-new -o BatchMode=yes -o ConnectTimeout=15 \
      -T git@github.com 2>&1 || true)"
  case "${probe}" in
    *"successfully authenticated"*) return 0 ;;
  esac

  warn "${identity} exists but github.com did not accept it; add the public half:"
  printf '    gh auth refresh -h github.com -s admin:public_key\n'
  printf '    gh ssh-key add %s.pub --title "$(hostname -s)"\n' "${identity}"
  printf '  (or paste it at https://github.com/settings/keys)\n'
}
